package me.anno.zauberei.types

enum class ScopeType {
    NORMAL_CLASS,
    INLINE_CLASS,
    INTERFACE,
    ENUM_CLASS,
    ENUM_ENTRY_CLASS,
    FUNCTION,
    CONSTRUCTOR,
    CONSTRUCTOR_PARAMS,
    PRIMARY_CONSTRUCTOR,
    OBJECT,
    FIELD_GETTER,
    FIELD_SETTER,
    LAMBDA,
    WHEN_CASES,
    EXPRESSION,
    PACKAGE,
    TYPE_ALIAS
}